### ISSUE TITLE
how to install the bitmap package?

### ISSUE THREAD

**Issue by scsolaris** [QBV-tu-ilmenau/Triangle-Mesh-Rasterization-Projection#1]
CMake Error at CMakeLists.txt:13 (find_package):
  By not providing "Findbitmap.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "bitmap", but
  CMake did not find one.

  Could not find a package configuration file provided by "bitmap" with any
  of the following names:

    bitmapConfig.cmake
    bitmap-config.cmake

  Add the installation prefix of "bitmap" to CMAKE_PREFIX_PATH or set
  "bitmap_DIR" to a directory containing one of the above files.  If "bitmap"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by waldflaufer** [comment]
Dear @scsolaris 

This is the usual procedure to build and install a CMake lib:

```
cmake -DCMAKE_INSTALL_PREFIX=/path/to/install/dir /path/to/source/dir
cmake --build .
cmake --install .
```

Please clone the [bitmap](
https://github.com/bebuch/bitmap) repository again, it has been updated.
However, the update has nothing to do with your problem.

**Comment by waldflaufer** [comment]
Dear @scsolaris 

We have made a simplification:
Now bitmap lib is then part of the project.

Best Regards
